name: Daily Wordle Word Generation

on:
  schedule:
    # Run daily at midnight UTC (00:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-daily-word:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate new daily word
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: node scripts/generate_word.js
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/today_word.json data/used_words.json
        git diff --staged --quiet || git commit -m "🎯 Generated new daily word for $(date +'%Y-%m-%d')"
        git push
